// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"wechat-ocr/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/ping",
				Handler: pingInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/test",
				Handler: testInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/pickupInfo",
				Handler: pickupInfoHandler(serverCtx),
			},
		},
	)
}
